import { NextResponse } from "next/server";
import connect from "@/utils/db";
import Post from "@/models/User";
import bcrypt from "bcryptjs";

export const GET = async (request) => {
  const url = new URL(request.url);

  const email = url.searchParams.get("email");

  try {
    await connect();

    const posts = await Post.find(email && { email });

    return new NextResponse(JSON.stringify(posts), { status: 200 });
  } catch (err) {
    return new NextResponse("Database Error", { status: 500 });
  }
};

export const POST = async (request) => {
  const {nombre, apellido, cedula, email, password, edad, seccion, curso_actual, notas, matematica_1_1,
  matematica_1_2,
  matematica_1_3,
  matematica_2_1,
  matematica_2_2,
  matematica_2_3,
  matematica_3_1,
  matematica_3_2,
  matematica_3_3,
  matematica_4_1,
  matematica_4_2,
  matematica_4_3,
  matematica_5_1,
  matematica_5_2,
  matematica_5_3,
  deporte_1_1,
  deporte_1_2,
  deporte_1_3,
  deporte_2_1,
  deporte_2_2,
  deporte_2_3,
  deporte_3_1,
  deporte_3_2,
  deporte_3_3,
  deporte_4_1,
  deporte_4_2,
  deporte_4_3,
  deporte_5_1,
  deporte_5_2,
  deporte_5_3,
  orientacion_1_1,
  orientacion_1_2,
  orientacion_1_3,
  orientacion_2_1,
  orientacion_2_2,
  orientacion_2_3,
  orientacion_3_1,
  orientacion_3_2,
  orientacion_3_3,
  orientacion_4_1,
  orientacion_4_2,
  orientacion_4_3,
  orientacion_5_1,
  orientacion_5_2,
  orientacion_5_3,
  grupo_estable_1_1,
  grupo_estable_1_2,
  grupo_estable_1_3,
  grupo_estable_2_1,
  grupo_estable_2_2,
  grupo_estable_2_3,
  grupo_estable_3_1,
  grupo_estable_3_2,
  grupo_estable_3_3,
  grupo_estable_4_1,
  grupo_estable_4_2,
  grupo_estable_4_3,
  grupo_estable_5_1,
  grupo_estable_5_2,
  grupo_estable_5_3,
  ghc_1_1,
  ghc_1_2,
  ghc_1_3,
  ghc_2_1,
  ghc_2_2,
  ghc_2_3,
  ghc_3_1,
  ghc_3_2,
  ghc_3_3,
  ghc_4_1,
  ghc_4_2,
  ghc_4_3,
  ghc_5_1,
  ghc_5_2,
  ghc_5_3,
  castellano_1_1,
  castellano_1_2,
  castellano_1_3,
  castellano_2_1,
  castellano_2_2,
  castellano_2_3,
  castellano_3_1,
  castellano_3_2,
  castellano_3_3,
  castellano_4_1,
  castellano_4_2,
  castellano_4_3,
  castellano_5_1,
  castellano_5_2,
  castellano_5_3,
  ingles_1_1,
  ingles_1_2,
  ingles_1_3,
  ingles_2_1,
  ingles_2_2,
  ingles_2_3,
  ingles_3_1,
  ingles_3_2,
  ingles_3_3,
  ingles_4_1,
  ingles_4_2,
  ingles_4_3,
  ingles_5_1,
  ingles_5_2,
  ingles_5_3,
  quimica_1_1,
  quimica_1_2,
  quimica_1_3,
  quimica_2_1,
  quimica_2_2,
  quimica_2_3,
  quimica_3_1,
  quimica_3_2,
  quimica_3_3,
  quimica_4_1,
  quimica_4_2,
  quimica_4_3,
  quimica_5_1,
  quimica_5_2,
  quimica_5_3,
  biologia_3_1,
  biologia_3_2,
  biologia_3_3,
  biologia_4_1,
  biologia_4_2,
  biologia_4_3,
  biologia_5_1,
  biologia_5_2,
  biologia_5_3,
  fisica_3_1,
  fisica_3_2,
  fisica_3_3,
  fisica_4_1,
  fisica_4_2,
  fisica_4_3,
  fisica_5_1,
  fisica_5_2,
  fisica_5_3,
  ciencias_naturales_1_1,
  ciencias_naturales_1_2,
  ciencias_naturales_1_3,
  ciencias_naturales_2_1,
  ciencias_naturales_2_2,
  ciencias_naturales_2_3,
  arte_convivencia_1_1,
  arte_convivencia_1_2,
  arte_convivencia_1_3,
  arte_convivencia_2_1,
  arte_convivencia_2_2,
  arte_convivencia_2_3,
  soberania_4_1,
  soberania_4_2,
  soberania_4_3,
  soberania_5_1,
  soberania_5_2,
  soberania_5_3,
  ciencias_tierra_5_1,
  ciencias_tierra_5_2,
  ciencias_tierra_5_3
} = await request.json();
  // const body = await request.json();
  console.log({nombre, apellido, cedula, email, password, edad, seccion, curso_actual, notas, matematica_1_1});
  await connect();

  const hashedPassword = await bcrypt.hash(password, 5);

  const newUser = new Post({
    nombre,
    apellido,
    email,
    cedula,
    password: hashedPassword,
    edad,
    seccion,
    curso_actual,
    notas,
    matematica_1_1,
    matematica_1_2,
    matematica_1_3,
    matematica_2_1,
    matematica_2_2,
    matematica_2_3,
    matematica_3_1,
    matematica_3_2,
    matematica_3_3,
    matematica_4_1,
    matematica_4_2,
    matematica_4_3,
    matematica_5_1,
    matematica_5_2,
    matematica_5_3,
    deporte_1_1,
    deporte_1_2,
    deporte_1_3,
    deporte_2_1,
    deporte_2_2,
    deporte_2_3,
    deporte_3_1,
    deporte_3_2,
    deporte_3_3,
    deporte_4_1,
    deporte_4_2,
    deporte_4_3,
    deporte_5_1,
    deporte_5_2,
    deporte_5_3,
    orientacion_1_1,
    orientacion_1_2,
    orientacion_1_3,
    orientacion_2_1,
    orientacion_2_2,
    orientacion_2_3,
    orientacion_3_1,
    orientacion_3_2,
    orientacion_3_3,
    orientacion_4_1,
    orientacion_4_2,
    orientacion_4_3,
    orientacion_5_1,
    orientacion_5_2,
    orientacion_5_3,
    grupo_estable_1_1,
    grupo_estable_1_2,
    grupo_estable_1_3,
    grupo_estable_2_1,
    grupo_estable_2_2,
    grupo_estable_2_3,
    grupo_estable_3_1,
    grupo_estable_3_2,
    grupo_estable_3_3,
    grupo_estable_4_1,
    grupo_estable_4_2,
    grupo_estable_4_3,
    grupo_estable_5_1,
    grupo_estable_5_2,
    grupo_estable_5_3,
    ghc_1_1,
    ghc_1_2,
    ghc_1_3,
    ghc_2_1,
    ghc_2_2,
    ghc_2_3,
    ghc_3_1,
    ghc_3_2,
    ghc_3_3,
    ghc_4_1,
    ghc_4_2,
    ghc_4_3,
    ghc_5_1,
    ghc_5_2,
    ghc_5_3,
    castellano_1_1,
    castellano_1_2,
    castellano_1_3,
    castellano_2_1,
    castellano_2_2,
    castellano_2_3,
    castellano_3_1,
    castellano_3_2,
    castellano_3_3,
    castellano_4_1,
    castellano_4_2,
    castellano_4_3,
    castellano_5_1,
    castellano_5_2,
    castellano_5_3,
    ingles_1_1,
    ingles_1_2,
    ingles_1_3,
    ingles_2_1,
    ingles_2_2,
    ingles_2_3,
    ingles_3_1,
    ingles_3_2,
    ingles_3_3,
    ingles_4_1,
    ingles_4_2,
    ingles_4_3,
    ingles_5_1,
    ingles_5_2,
    ingles_5_3,
    quimica_1_1,
    quimica_1_2,
    quimica_1_3,
    quimica_2_1,
    quimica_2_2,
    quimica_2_3,
    quimica_3_1,
    quimica_3_2,
    quimica_3_3,
    quimica_4_1,
    quimica_4_2,
    quimica_4_3,
    quimica_5_1,
    quimica_5_2,
    quimica_5_3,
    biologia_3_1,
    biologia_3_2,
    biologia_3_3,
    biologia_4_1,
    biologia_4_2,
    biologia_4_3,
    biologia_5_1,
    biologia_5_2,
    biologia_5_3,
    fisica_3_1,
    fisica_3_2,
    fisica_3_3,
    fisica_4_1,
    fisica_4_2,
    fisica_4_3,
    fisica_5_1,
    fisica_5_2,
    fisica_5_3,
    ciencias_naturales_1_1,
    ciencias_naturales_1_2,
    ciencias_naturales_1_3,
    ciencias_naturales_2_1,
    ciencias_naturales_2_2,
    ciencias_naturales_2_3,
    arte_convivencia_1_1,
    arte_convivencia_1_2,
    arte_convivencia_1_3,
    arte_convivencia_2_1,
    arte_convivencia_2_2,
    arte_convivencia_2_3,
    soberania_4_1,
    soberania_4_2,
    soberania_4_3,
    soberania_5_1,
    soberania_5_2,
    soberania_5_3,
    ciencias_tierra_5_1,
    ciencias_tierra_5_2,
    ciencias_tierra_5_3
    
  });

  // const newUser = new Post(body)

  try {

    await newUser.save();

    return new NextResponse("Post has been created", { status: 201 });
  } catch (err) {
    return new NextResponse("Database Error", { status: 500 });
  }
};